### ISSUE TITLE
`ModuleNotFoundError: No module named 'pydantic.v1'`

### ISSUE THREAD

**Issue by adi-** [monim67/django-flatpickr#19]
Although I have pydantic 2.0a3 installed I get error `ModuleNotFoundError: No module named 'pydantic.v1'`.

```bash
Traceback (most recent call last):
  File "/home/vagrant/.venv/lib/python3.8/site-packages/django_flatpickr/settings.py", line 8, in <module>
    from pydantic.v1 import Field
ModuleNotFoundError: No module named 'pydantic.v1'

...
  File "/home/vagrant/.venv/lib/python3.8/site-packages/django_flatpickr/_media.py", line 4, in <module>
    from django_flatpickr.settings import DjangoFlatpickrSettings
  File "/home/vagrant/.venv/lib/python3.8/site-packages/django_flatpickr/settings.py", line 12, in <module>
    from pydantic.env_settings import (  # type: ignore
ImportError: cannot import name 'BaseSettings' from 'pydantic.env_settings' (/home/vagrant/.venv/lib/python3.8/site-packages/pydantic/env_settings.py)

```

**Comment by adi-** [comment]
Problem is on version `2.0.2` and `2.0.3`

**Comment by monim67** [comment]
Checked the pydantic release history: `2.0a3` was a pre-release alpha (Apr 2023), published over two months before stable pydantic `2.0` (Jun 2023) shipped the `pydantic.v1` compat shim this package relies on. This doesn't reproduce on any stable pydantic release supported by `pydantic>=1,<3` — closing as not reproducible on a supported version.
